-- Create some example users
INSERT INTO [UserProfile] ([Name], [Email], [FirebaseUserId], [ImageUrl], [DateCreated])
VALUES
('Peter Parker', 'peterparker@example.com', 6789, 'https://example.com/peterparker.jpg', GETDATE()),
('Clark Kent', 'clarkkent@example.com', 7890, 'https://example.com/clarkkent.jpg', GETDATE()),
('Bruce Wayne', 'brucewayne@example.com', 8901, 'https://example.com/brucewayne.jpg', GETDATE()),
('Tony Stark', 'tonystark@example.com', 9012, 'https://example.com/tonystark.jpg', GETDATE()),
('Steve Rogers', 'steverogers@example.com', 1234, 'https://example.com/steverogers.jpg', GETDATE()),
('Thor Odinson', 'thorodinson@example.com', 2345, 'https://example.com/thorodinson.jpg', GETDATE()),
('Diana Prince', 'dianaprince@example.com', 3456, 'https://example.com/dianaprince.jpg', GETDATE()),
('Barry Allen', 'barryallen@example.com', 4567, 'https://example.com/barryallen.jpg', GETDATE()),
('Hal Jordan', 'haljordan@example.com', 5678, 'https://example.com/haljordan.jpg', GETDATE()),
('Wade Wilson', 'wade wilson@example.com', 6789, 'https://example.com/wadewilson.jpg', GETDATE()),
('Peter Quill', 'peter quill@example.com', 7890, 'https://example.com/peterquill.jpg', GETDATE()),
('TChalla', 'tchalla@example.com', 8901, 'https://example.com/tchalla.jpg', GETDATE())


-- Create some example subjects
INSERT INTO [Subject] ([Name])
VALUES
('JavaScript'),
('Python'),
('Java'),
('C#'),
('C++'),
('TypeScript'),
('HTML/CSS'),
('Algorithms'),
('Data Structures'),
('Operating Systems'),
('Computer Networks'),
('Databases'),
('Software Engineering'),
('Web Development'),
('Machine Learning'),
('Artificial Intelligence'),
('Cryptography'),
('Computer Security'),
('Natural Language Processing'),
('Computer Graphics'),
('Swift'),
('Kotlin'),
('Go'),
('Rust'),
('PHP'),
('Ruby'),
('Perl'),
('C'),
('R'),
('React.js'), 
('Vue.js'), 
('Angular.js'), 
('jQuery'), 
('Bootstrap'), 
('Lodash'), 
('Moment.js'), 
('Express.js'), 
('Django'), 
('Flask'), 
('Ruby on Rails'), 
('ASP.NET'), 
('Symfony'), 
('Spring'), 
('Next.js'), 
('Nuxt.js'), 
('Gatsby'), 
('Materialize'), 
('Bulma'), 
('Tailwind CSS')


-- Create some example media types
INSERT INTO [MediaType] ([Name])
VALUES
('Online course'),
('E-book'),
('Book'),
('Video series'),
('Website'),
('Podcast'),
('Meetup'),
('Bootcamp'),
('Conference'),
('Blog'),
('Research paper'),
('Tutorial'),
('Online documentation')

-- Create some example resources
INSERT INTO [Resource] ([Name], [SubmitterId], [Creator], [MediaTypeId], [Description], [Price], [DatePublished], [ImageUrl], [ResourceUrl])
VALUES
('JavaScript for Beginners', 15, 'Bob Smith', 1, 'An online course teaching the basics of JavaScript programming', 49.99, '2021-01-15', 'https://example.com/js-for-beginners.jpg', 'https://example.com/js-for-beginners'),
('Learning Python', 2, 'Jane Doe', 2, 'A book covering the fundamentals of Python programming', 29.99, '2020-11-01', 'https://example.com/learning-python.jpg', 'https://example.com/learning-python'),
('Java Programming Masterclass', 3, 'John Smith', 4, 'A video series covering advanced topics in Java programming', 99.99, '2021-02-10', 'https://example.com/java-masterclass.jpg', 'https://example.com/java-masterclass'),
('C++ Primer', 4, 'David Johnson', 3, 'A comprehensive guide to C++ programming', 39.99, '2020-09-21', 'https://example.com/c-plus-plus-primer.jpg', 'https://example.com/c-plus-plus-primer'),
('TypeScript in 30 Days', 5, 'Sarah Lee', 1, 'An online course teaching TypeScript programming in 30 days', 79.99, '2021-03-20', 'https://example.com/typescript-30-days.jpg', 'https://example.com/typescript-30-days'),
('HTML and CSS: Design and Build Websites', 6, 'Jack Brown', 2, 'A book that teaches how to design and build websites using HTML and CSS', 24.99, '2020-12-05', 'https://example.com/html-css-design.jpg', 'https://example.com/html-css-design'),
('Algorithms: Design and Analysis, Part 1', 7, 'Emily Chen', 3, 'A book covering the design and analysis of algorithms', 35.99, '2021-05-01', 'https://example.com/algorithms-design.jpg', 'https://example.com/algorithms-design'),
('Data Structures and Algorithms with Python', 8, 'Mike Williams', 4, 'A video series teaching data structures and algorithms using Python', 89.99, '2021-04-10', 'https://example.com/data-structures-algorithms.jpg', 'https://example.com/data-structures-algorithms'),
('Operating Systems Concepts', 9, 'Kelly Brown', 2, 'A book covering the fundamental concepts of operating systems', 44.99, '2020-10-15', 'https://example.com/os-concepts.jpg', 'https://example.com/os-concepts'),
('Computer Networks: A Systems Approach', 10, 'Tom Anderson', 1, 'An online course covering the fundamentals of computer networks', 59.99, '2021-02-01', 'https://example.com/computer-networks.jpg', 'https://example.com/computer-networks'),
('Software Engineering: A Practitioner''s Approach', 12, 'Tom Lee', 2, 'A book covering the principles and practices of software engineering', 29.99, '2020-08-01', 'https://example.com/software-engineering.jpg', 'https://example.com/software-engineering'),
('Machine Learning with TensorFlow', 13, 'John Smith', 4, 'A video series teaching machine learning using TensorFlow', 99.99, '2021-03-10', 'https://example.com/tensorflow-machine-learning.jpg', 'https://example.com/tensorflow-machine-learning'),
('Natural Language Processing with Python', 14, 'David Johnson', 3, 'A book covering the fundamentals of natural language processing using Python', 39.99, '2020-10-21', 'https://example.com/nlp-python.jpg', 'https://example.com/nlp-python'),
('Computer Vision with OpenCV', 15, 'Sarah Lee', 1, 'An online course teaching computer vision using OpenCV', 79.99, '2021-04-20', 'https://example.com/computer-vision-opencv.jpg', 'https://example.com/computer-vision-opencv'),
('Deep Learning with PyTorch', 6, 'Jack Brown', 2, 'A book covering the fundamentals of deep learning using PyTorch', 24.99, '2020-12-06', 'https://example.com/deep-learning-pytorch.jpg', 'https://example.com/deep-learning-pytorch'),
('Artificial Intelligence: A Modern Approach', 7, 'Emily Chen', 3, 'A comprehensive textbook on artificial intelligence', 35.99, '2021-06-01', 'https://example.com/ai-modern-approach.jpg', 'https://example.com/ai-modern-approach'),
('Machine Learning for Beginners', 8, 'Mike Williams', 4, 'An online course teaching the basics of machine learning', 89.99, '2021-05-10', 'https://example.com/machine-learning-beginners.jpg', 'https://example.com/machine-learning-beginners'),
('Deep Reinforcement Learning', 9, 'Kelly Brown', 2, 'A book covering the fundamentals of deep reinforcement learning', 44.99, '2020-11-15', 'https://example.com/deep-reinforcement-learning.jpg', 'https://example.com/deep-reinforcement-learning'),
('Natural Language Generation with Bard', 10, 'Tom Anderson', 1, 'An online course teaching natural language generation using Bard', 59.99, '2021-03-01', 'https://example.com/nlg-bard.jpg', 'https://example.com/nlg-bard'),
('Computer Vision with TensorFlow', 11, 'Emily Kim', 3, 'A video series teaching computer vision using TensorFlow', 119.99, '2021-04-15', 'https://example.com/cv-tensorflow.jpg', 'https://example.com/cv-tensorflow'),
('Machine Learning with PyTorch', 12, 'Tom Lee', 2, 'A book covering the fundamentals of machine learning using PyTorch', 29.99, '2020-09-01', 'https://example.com/ml-pytorch.jpg', 'https://example.com/ml-pytorch'),
('Mastering Databases with SQL', 11, 'Emily Kim', 3, 'A video series teaching SQL and database design', 119.99, '2021-03-15', 'https://example.com/sql-databases.jpg', 'https://example.com/sql-databases'),
('Software Engineering', 12, 'Sarah Johnson', 3, 'A book covering the fundamentals of software engineering', 59.99, '2021-06-01', 'https://example.com/software-engineering.jpg', 'https://example.com/software-engineering'),
('Databases with SQL', 10, 'Michael Brown', 2, 'A comprehensive guide to databases and SQL', 39.99, '2021-07-15', 'https://example.com/databases.jpg', 'https://example.com/databases'),
('Computer Networks', 15, 'James Smith', 3, 'A comprehensive guide to computer networks and protocols', 54.99, '2021-08-01', 'https://example.com/networks.jpg', 'https://example.com/networks'),
('Operating Systems', 14, 'Benjamin Lee', 3, 'A comprehensive guide to operating systems concepts', 49.99, '2021-09-15', 'https://example.com/operating-systems.jpg', 'https://example.com/operating-systems'),
('Data Structures in Python', 13, 'Rachel Kim', 2, 'A book covering various data structures using Python', 29.99, '2022-05-01', 'https://example.com/data-structures.jpg', 'https://example.com/data-structures'),
('Algorithms and Data Structures', 12, 'Alex Johnson', 2, 'A comprehensive guide to algorithms and data structures', 44.99, '2021-10-15', 'https://example.com/algorithms.jpg', 'https://example.com/algorithms'),
('HTML and CSS', 15, 'Mary Brown', 1, 'A beginners guide to building websites with HTML and CSS', 12.99, '2022-04-01', 'https://example.com/html-css.jpg', 'https://example.com/html-css'),
('TypeScript Programming', 7, 'David Kim', 1, 'An introduction to TypeScript programming language', 14.99, '2022-03-15', 'https://example.com/typescript.jpg', 'https://example.com/typescript'),
('C++ Programming', 11, 'Samantha Lee', 2, 'A deep dive into C++ programming language', 39.99, '2021-12-01', 'https://example.com/cpp.jpg', 'https://example.com/cpp'),
('C# Programming', 8, 'Mike Johnson', 1, 'An introduction to C# programming language', 19.99, '2022-02-28', 'https://example.com/c-sharp.jpg', 'https://example.com/c-sharp'),
('Java Programming', 10, 'Emily Jones', 2, 'A comprehensive guide to Java programming language', 34.99, '2021-11-15', 'https://example.com/java.jpg', 'https://example.com/java'),
('Python Programming', 9, 'John Smith', 1, 'A beginners guide to programming with Python', 24.99, '2022-01-01', 'https://example.com/python.jpg', 'https://example.com/python')